[tool.black]
line-length = 88
target-version = ['py311']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | data
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["src"]
skip = ["data", "__pycache__"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503", "E501", "F401", "F841", "E402", "F541"]
exclude = [
    ".git",
    "__pycache__",
    "data",
    ".venv",
    "venv",
    "build",
    "dist"
]
